app/WebApp/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField,SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_login import current_user
from WebApp.models import User



class RegistrationRequestForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])

    submit = SubmitField('Request Registration')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('That email is taken. Please choose a different one.')


class LoginForm(FlaskForm):

    username = StringField('Username',
                        validators=[DataRequired()])

    password = PasswordField('Password',
                             validators=[DataRequired()])

    remember = BooleanField('Remember Me')
    
    submit = SubmitField('Login')

    
class UpdateAccountForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(),Length(min=2, max=20)])

    email = StringField('Email',
                        validators=[DataRequired(), Email()])

    picture = FileField("Update Profile Picture", validators=[FileAllowed(['jpg', 'png'])])


    submit = SubmitField('Update')

        # custom validators
    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError('That username is taken. Please choose a different one.')

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError('That email is taken. Please choose a different one.')

class RequestResetForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])

    submit = SubmitField('Request Password Reset')
    
    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError('There is no account with that email. You must register first.')

class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password',
                             validators=[DataRequired()])

    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), EqualTo('password')])

    submit = SubmitField('Reset Password')

app/WebApp/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from WebApp import db, bcrypt
from WebApp.models import User, Link, access, Role
from WebApp.users.forms import (LoginForm, UpdateAccountForm,
                                RequestResetForm, ResetPasswordForm,
                                RegistrationRequestForm)
from WebApp.users.utils import save_picture, send_reset_email, send_email, send_log
import datetime

users= Blueprint('users', __name__)


@users.route('/login', methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            now_log = datetime.datetime.now()
            send_log(f'{current_user.username}, logged in, {now_log}', 'authentication')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('user/login.html', title='Login', form=form)

@users.route('/logout')
def logout():
    now_log = datetime.datetime.now()
    send_log(f'{current_user.username}, logged out, {now_log}', 'authentication')

    logout_user()
    return redirect(url_for('main.home'))

@users.route('/request_register', methods=['GET', 'POST'])
def register():
    form = RegistrationRequestForm()
    if form.validate_on_submit():
        admins = User.query.filter_by(is_admin=True)
        receiver = [admin.email for admin in admins]
        #receiver = '{}'.format([admin.email for admin in admins])
        message = """MIME-Version: 1.0
Content-type: text/html
Subject: Grenada Intranet Request User Registry
Someone is requesting registration to the Grenada Intranet Site their email is {}""".format(form.email.data)
        #send_email(receiver, message)
        return f"{receiver}"
        
        #flash('Your request for access will be processed. Please watch your email for updates', 'success')
        #return redirect(url_for('main.home'))
    return render_template('user/registration.html', form=form)


@users.route('/account', methods=['GET','POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Your account has been updated!", "success")
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='ProfilePics/' + current_user.image_file)
    return render_template('user/account.html', title='Account', image_file=image_file, form=form)


@users.route('/reset_password', methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('user/reset_request.html', title='Reset Password', form=form)

@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been changed. You are able to log in!', 'success')
        return redirect(url_for('users.login'))
    return render_template('user/reset_token.html', title='Reset Password', form=form)

app/WebApp/templates/user/account.html
{% extends "layout.html" %}
{% block content %}
	<div class="container">
		<div class="media">
			<img class="rounded-circle account-img" src="{{image_file}}">
			<div class="media-body">
				<h2 class="account-heading">{{ current_user.username }}</h2>
				<p class="text-secondary">{{ current_user.email }}</p>
			</div>
		</div>
	</div>
		<!-- FORM HERE-->
	<div class="container">
		<form method="POST" action="", enctype="multipart/form-data">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottm mb-4"> Account Information</legend>

				<div class="form-group">
					{{ form.username.label(class="form-control-label") }}

					{% if form.username.errors %}
						{{ form.username(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.username.errors %}
								<span> {{ error }} </span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.username(class="form-control form-control-lg") }}
					{% endif %}
				</div>

				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span> {{ error }} </span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>

				<div class="form-group">
					{{ form.picture.label() }}
					{{ form.picture(class="form-control-file") }}
					{% if form.picture.errors %}
						{% for error in form.picture.errors %}
							<span class="text-danger">{{error}}</span></br>
						{% endfor %}
					{% endif %}
				</div>

			</fieldset>

			<div class="form-group">
					{{ form.submit(class="btn btn-outline-info") }}
				</div>
		</form>
	</div>
{% endblock content %}

app/WebApp/templates/user/login.html
{% extends "layout.html" %}
{% block content %}
	<div class="container">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottm mb-4"> Log In</legend>

				<div class="form-group">
					{{ form.username.label(class="form-control-label") }}
					{% if form.username.errors %}
						{{ form.username(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.username.errors %}
								<span> {{ error }} </span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.username(class="form-control form-control-lg") }}
					{% endif %}
				</div>

				<div class="form-group">
					{{ form.password.label(class="form-control-label") }}
					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span> {{ error }} </span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}
				</div>

				<div class="form-group">
					{{ form.remember(class='form-check-input') }}
					{{ form.remember.label(class="form-check-label") }}
				</div>


				
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>

			<small class="text-muted ml-2">
				<a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
			</small>
		</form>
	</div>

	<div class="border-top pt-3">
		<small class="text-muted">
			Need an Account? <a class="ml-2" href="{{url_for('users.register')}}">Request to be registered.</a>
		</small>
	</div>
{% endblock content %}

app/WebApp/templates/user/login1.html
{% extends "layout.html" %}
{% block content %}
	<div class="container">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottm mb-4"> Log In</legend>

				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span> {{ error }} </span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>

				<div class="form-group">
					{{ form.password.label(class="form-control-label") }}
					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span> {{ error }} </span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}
				</div>

				<div class="form-group">
					{{ form.remember(class='form-check-input') }}
					{{ form.remember.label(class="form-check-label") }}
				</div>


				
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>

			<small class="text-muted ml-2">
				<a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
			</small>
		</form>
	</div>

	<div class="border-top pt-3">
		<small class="text-muted">
			Need an Account? <a class="ml-2" href="{{url_for('users.register')}}">Request to be registered.</a>
		</small>
	</div>
{% endblock content %}

app/WebApp/templates/user/mill_log.html
{% extends "layout.html" %}
{% block content %}
	<h1>Mill Log PAGE</h1>
{% endblock content %}

app/WebApp/templates/user/mill_log_new.html
{% extends "layout.html" %}
{% block content %}
	<h1>Mill Log New Entry PAGE</h1>
{% endblock content %}

app/WebApp/templates/user/registration.html
{% extends "layout.html" %}
{% block content %}
	<div class="container">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottm mb-4"> Request Registration</legend>

				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span> {{ error }} </span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
			</fieldset>
			
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>

		</form>
	</div>

{% endblock content %}

app/WebApp/templates/user/reset_request.html
{% extends "layout.html" %}
{% block content %}
	<div class="container">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottm mb-4"> Reset Password</legend>

				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span> {{ error }} </span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
			</fieldset>
			
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>

		</form>
	</div>

{% endblock content %}

app/WebApp/templates/user/reset_token.html
{% extends "layout.html" %}
{% block content %}
	<div class="container">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottm mb-4"> Reset Password</legend>

				<div class="form-group">
					{{ form.password.label(class="form-control-label") }}
					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span> {{ error }} </span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				
				<div class="form-group">
					{{ form.confirm_password.label(class="form-control-label") }}
					{% if form.confirm_password.errors %}
						{{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.confirm_password.errors %}
								<span> {{ error }} </span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.confirm_password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				
			</fieldset>
			
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>

		</form>
	</div>

{% endblock content %}