app/WebApp/admin/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, Blueprint,
                   jsonify, abort)
from operator import attrgetter
from flask_login import login_user, current_user, logout_user, login_required
from WebApp import db, bcrypt
from WebApp.models import User, Link, Role
from WebApp.admin.forms import (RegistrationForm, RoleForm,
                                PermissionForm, RoleModForm,
                                NewLinkForm, UpdateLinkForm)
from WebApp.admin.utils import available_roles, available_rights

admin = Blueprint('admin', __name__)


@admin.route('/links/new', methods=('GET','POST'))
def new_links():
    form = NewLinkForm()
    if form.validate_on_submit():
        link = Link(linkname=form.linkname.data, url=form.url.data, group=form.group.data)
        db.session.add(link)
        db.session.commit()
        flash('link has been created', 'success')
        return redirect(url_for('main.home'))
    return render_template('admin/new_links.html', legend='Create Link', title='New Links', form=form)

@admin.route('/links/<int:link_id>/update', methods=('GET','POST'))
@login_required
def update_links(link_id):
    link = Link.query.get_or_404(link_id)
    if not current_user.is_admin:
        abort(403)

    form = UpdateLinkForm()
    if request.method == 'GET':
        form.linkname.data = link.linkname
        form.url.data = link.url
        form.group.data = link.group
    elif form.validate_on_submit():
        link.linkname = form.linkname.data
        link.url = form.url.data
        link.group = form.group.data
        db.session.commit()
        flash('Link has been updated', 'success')
        return redirect(url_for('main.home'))
    return render_template('admin/update_links.html', title='New Link', legend='Update Link', form=form)

@admin.route('/links/<int:link_id>/delete', methods=('GET','POST'))
@login_required
def delete_links(link_id):
    link = Link.query.get_or_404(link_id)
    if not current_user.is_admin:
        abort(403)
    db.session.delete(link)
    db.session.commit()
    
    flash('Link was delete from database', 'success')
    return redirect(url_for('main.home'))


    
@admin.route('/permissions', methods=('GET', 'POST'))
def permissions():
    if not current_user.is_authenticated:
        return redirect(url_for('users.login'))
    elif not current_user.is_admin:
        return redirect(url_for('main.home'))
    form = PermissionForm()
    if request.method == 'GET':
        users = User.query.all()
        users.sort(key=attrgetter('username'))
        form.username.choices = [(int(user.id), user.username) for user in users]   
        user = users[0]
        roles = Role.query.all()
        rights = user.rights
        availables = available_roles(roles, user)
        form.roles.choices = [(int(available.id), available.group) for available in availables]
        form.assigned.choices = [(int(right.id), right.group) for right in user.rights]
    elif request.method == 'POST':
        form_username = []
        form_roles = []
        form_assigned = []
        form_username = form.username.data
        form_roles = form.roles.data
        form_assigned = form.assigned.data
        user = User.query.filter_by(id=form_username).first()
        if form_roles is not None:
            role_ids = form_roles
            roles = [Role.query.filter_by(id=role_id).first() for role_id in role_ids] 
            availables = available_rights(roles, user)
            if isinstance(availables, list):
                for available in availables:
                    try:
                        user.rights.remove(available)
                    except:
                        pass
            else:
                    try:
                        user.rights.remove(availables)
                    except:
                        pass
            
        if form_assigned is not None:
            assigned_ids = form_assigned
            assigned = [Role.query.filter_by(id=assigned_id).first() for assigned_id in assigned_ids]
            assignables = available_roles(assigned, user)
            if isinstance(assignables, list):
                for assignable in assignables:
                        try:
                            user.rights.append(assignable)
                        except:
                            pass
            else:
                    try:
                        user.rights.append(assignables)
                    except:
                        pass
            flash('Permissions for {} have been updated.'.format(user.username), 'success')
        db.session.commit()
        return redirect(url_for('admin.permissions'))
    
    return render_template('admin/permissions.html', title='Permissions', form=form)

@admin.route('/permissions_user/<username_id>')
def permissions_user(username_id):
    user = User.query.filter_by(id=username_id).first()
    rights = user.rights
    roles = Role.query.all()
    availables = available_roles(roles, user)
    
        # create export objects
    rights_objs = []
    availables_objs = []
    for right in rights:
        obj = {}
        obj['id'] = '{}'.format(right.id)
        obj['group'] = '{}'.format(right.group)
        rights_objs.append(obj)

    for available in availables:
        obj = {}
        obj['id'] = '{}'.format(available.id)
        obj['group'] = '{}'.format(available.group)
        availables_objs.append(obj)
        
    return jsonify(rights_objs, availables_objs)

@admin.route('/new_roles', methods=('GET', 'POST'))
def new_roles():
    if not current_user.is_authenticated:
        return redirect(url_for('users.login'))
    elif not current_user.is_admin:
        return redirect(url_for('main.home'))
    form = RoleForm()
    if form.validate_on_submit():
        role = Role(group=form.group.data, description=form.description.data)
        db.session.add(role)
        db.session.commit()
        flash('A new role as been created.', 'success')
        return redirect(url_for('admin.permissions'))
    return render_template('admin/new_roles.html', title='New Roles', form=form)

@admin.route('/roles', methods=('GET', 'POST'))
def roles():
    if not current_user.is_authenticated:
        return redirect(url_for('users.login'))
    elif not current_user.is_admin:
        return redirect(url_for('main.home'))
    form = RoleModForm()
    if request.method == "POST":
        role = []
        role = Role.query.filter_by(id=form.group.data).first()
        role.description = form.description.data
        db.session.commit()
        flash('a role has been updated ', 'success')
        return redirect(url_for('main.home'))
    elif request.method == "GET":
        form.group.choices = [(role.id, role.group) for role in Role.query.all()]
        role = Role.query.filter_by(id=1).first()
        form.description.data = role.description
        
    return render_template('admin/roles.html', title='Update Roles',form=form)

@admin.route('/roles_group/<group_id>')
def roles_group(group_id):
    role = Role.query.filter_by(id=group_id).first()
    obj = {}
    obj['id'] = '{}'.format(role.id)
    obj['group'] = '{}'.format(role.group)
    obj['description'] = '{}'.format(role.description)
    
    return jsonify(obj)

@admin.route('/register', methods=['GET','POST'])
def register():
    if not current_user.is_authenticated:
        return redirect(url_for("users.login"))
    elif not current_user.is_admin:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, is_admin=form.admin.data, password = hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created. You are able to log in.!', 'success')
        return redirect(url_for('users.login'))
    return render_template('admin/register.html', title='Register',form=form)

@admin.route('/admin/reset_password/<int:user_id>')
def password_reset(user_id):
    if not current_user.is_authenticated:
        return redirect(url_for("user.login"))
    elif not current_user.is_admin:
        return redirect(url_for('main.home'))

    pword = "Passw0rd"

    hashed_password = bcrypt.generate_password_hash(pword).decode('utf-8')
    user = User.query.filter_by(id=user_id).first()
    user.password = hashed_password
    db.session.commit()
    flash('Password has been reset to {}'.format(pword), 'success')
    return redirect(url_for('main.home'))

@admin.route('/admin/delete_user/<int:user_id>')
def delete_user(user_id):
    if not current_user.is_authenticated:
        return redirect(url_for('user.login'))
    elif not current_user.is_admin:
        return redirect(url_for('main.home'))

    user = User.query.filter_by(id=user_id).first()
    db.session.delete(user)
    db.session.commit()
    flash('{} has been deleted!'.format(user.username), 'success')
    return redirect(url_for('main.home'))
    

app/WebApp/dev_ops/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint


dev_ops = Blueprint('dev_ops', __name__)

@dev_ops.route('/api')
def api():
    return render_template('api.html')

@dev_ops.route('/api/new')
def api_new():
    return render_template('api_new.html')

app/WebApp/main/routes.py
from flask import render_template, request, Blueprint
from WebApp.models import Link
from WebApp.main.forms import DataSetForm
from flask_login import current_user, login_required

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
@main.route('/grenada')
def home():
    links = Link.query.all()
    groups = []
    for link in links:
        if not link.group in groups:
            groups.append(link.group)
            
    return render_template('home.html', groups=groups, links=links)

@main.route('/dashboard/')
@login_required
def dashboard():
    username = current_user.username
    user_id = current_user.id
    return render_template('dashboard.html', title=f"{username}'s Dashboard")

@main.route('/dashboard/widget/')
@login_required
def widgets():
    username = current_user.username
    user_id = current_user.id
    return render_template('widgets.html', title=f"{username}'s Widgets")

@main.route('/dashboard/dataset/')
@login_required
def dataSets():
    username = current_user.username
    user_id = current_user.id
    return render_template('dataSets.html', title=f"{username}'s Datasets")

@main.route('/dashboard/dataset/new')
@login_required
def dataSet_new():
    form = DataSetForm
    return render_template('dataSet_new.html', title='New Dataset', legend='Create Dataset', form=form)

app/WebApp/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from WebApp import db, bcrypt
from WebApp.models import User, Link, access, Role
from WebApp.users.forms import (LoginForm, UpdateAccountForm,
                                RequestResetForm, ResetPasswordForm,
                                RegistrationRequestForm)
from WebApp.users.utils import save_picture, send_reset_email, send_email, send_log
import datetime

users= Blueprint('users', __name__)


@users.route('/login', methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            now_log = datetime.datetime.now()
            send_log(f'{current_user.username}, logged in, {now_log}', 'authentication')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('user/login.html', title='Login', form=form)

@users.route('/logout')
def logout():
    now_log = datetime.datetime.now()
    send_log(f'{current_user.username}, logged out, {now_log}', 'authentication')

    logout_user()
    return redirect(url_for('main.home'))

@users.route('/request_register', methods=['GET', 'POST'])
def register():
    form = RegistrationRequestForm()
    if form.validate_on_submit():
        admins = User.query.filter_by(is_admin=True)
        receiver = [admin.email for admin in admins]
        #receiver = '{}'.format([admin.email for admin in admins])
        message = """MIME-Version: 1.0
Content-type: text/html
Subject: Grenada Intranet Request User Registry
Someone is requesting registration to the Grenada Intranet Site their email is {}""".format(form.email.data)
        #send_email(receiver, message)
        return f"{receiver}"
        
        #flash('Your request for access will be processed. Please watch your email for updates', 'success')
        #return redirect(url_for('main.home'))
    return render_template('user/registration.html', form=form)


@users.route('/account', methods=['GET','POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Your account has been updated!", "success")
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='ProfilePics/' + current_user.image_file)
    return render_template('user/account.html', title='Account', image_file=image_file, form=form)


@users.route('/reset_password', methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('user/reset_request.html', title='Reset Password', form=form)

@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been changed. You are able to log in!', 'success')
        return redirect(url_for('users.login'))
    return render_template('user/reset_token.html', title='Reset Password', form=form)

app/WebApp/templates/dashboard.html
{% extends 'layout.html' %}
{% block content %}	
	<div class='container'>
	
			<!-- 2nd Navbar -->
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark pre-scrollable ">

				<!-- Toggler -->
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar2Toggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
		
			<div class="collapse navbar-collapse" id="navbar2Toggle">
				<div class="container">
					<div class="navbar-nav mr-auto" id="nav2">
						<a id='aDashboard' class="nav-item nav-link active" href="{{url_for('main.dashboard')}}">Dashboard</a>
						<a id="aWidget" class="nav-item nav-link" href="{{url_for('main.widgets')}}">Widgets</a>
						<a id="aDataSet" class="nav-item nav-link" href="{{url_for('main.dataSets')}}">Data Sets</a>
					</div>	
				</div>
			</div>
		</nav>
		<br />
			
			<!-- Dashboard -->
		<div class="container">
			<a href="#" class="btn btn-outline-primary btn-md">Customize Dashbard</a>
			<div id="divDash"></div>
		</div>
	</div>
	
{% endblock content %}

app/WebApp/templates/dataSets.html
{% extends 'layout.html' %}
{% block content %}	
	<div class='container'>
	
			<!-- 2nd Navbar -->
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark pre-scrollable ">

				<!-- Toggler -->
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar2Toggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
		
			<div class="collapse navbar-collapse" id="navbar2Toggle">
				<div class="container">
					<div class="navbar-nav mr-auto" id="nav2">
						<a id='aDashboard' class="nav-item nav-link" href="{{url_for('main.dashboard')}}">Dashboard</a>
						<a id="aWidget" class="nav-item nav-link" href="{{url_for('main.widgets')}}">Widgets</a>
						<a id="aDataSet" class="nav-item nav-link active" href="{{url_for('main.dataSets')}}">Data Sets</a>
					</div>	
				</div>
			</div>
		</nav>
		<br />
			
			<!-- Data Sets -->
		<div class="container">
			<a href="#" class="btn btn-outline-primary btn-md">Create Data Set</a>
			<div id="divDataSets"></div>
		</div>
	</div>
	
{% endblock content %}

app/WebApp/templates/home.html
{% extends "layout.html" %}
{% block content %}

<div class="container">
	<h1>Grenada, MS</h1>
			<!-- Picture -->
	<div class="jumbotron" style="background-image: url({{ url_for('static', filename='GrenadaMill_Pic.jpg') }});">
	</div>

		<!-- Phone numbers -->
	<div class="container">
		<h1>Phone Numbers</h1>
		<hr />
		<div class="row">
			<div class="col-lg-3">
				<h3>Grenada Resolute Main Line</h3>
				<h3>662-227-7900</h3>
			</div>
			<div class="col-lg-3">
				<h3>Ethics and Accounting Reporting Hotline</h3>
				<h3>1-877-319-8904</h3>
			</div>
			<div class="col-lg-3" id="txtEmergency">
				<h3>In-House Emergency</h3>
				<h3>5911</h3>
			</div>
			<div class="col-lg-3">
				<h3>Scalehouse</h3>
				<h3>7939</h3>
			</div>
		</div>
	</div>
	
	<hr />
	<!--Temporary Use Only-->
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<h2>COVID19 Info</h2>
				<hr />
				<a class="btn btn-success btn-block btn-lg" role="button" href="https://resonet.resolutefp.com/corporate-services/human-resources/COVID-19/">Resolute COVID19 Information</a>
			</div>
		</div>
	</div>
	
	<hr />

	<!-- Links -->
	<div class="container">
		{% for group in groups %}
			<h2>{{ group }}</h2>
			<hr />
			{% for link in links%}
				{% if link.group == group %}
					<a class="btn btn-success btn-block btn-lg" role="button" href="{{ link.url }}">{{ link.linkname }}</a>
					{% if current_user.is_authenticated and current_user.is_admin %}
						<div>
							<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('admin.update_links', link_id=link.id) }}"> Update</a>
							<button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal{{link.id}}">Delete</button>
						</div>
						
							<!-- Modal -->

						<div class="modal fade" id="deleteModal{{link.id}}" tabindex="-1" role="dialog" aria-labelledby="deleteModallabel" aria-hidden="true">
							<div class="modal-dialog" role="document">
								<div class="modal-content">
									<div class="header">
										<h5 class="modal-title" id="deleteModallabel{{link.id}}">Delete Link</h5>
										<button type="button" class="close" data-dismiss="modal" aria-label="Close">
											<span aria-hidden="true">&times;</span>
										</button>
									</div>
									<div class="modal-footer">
										<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
										<form action="{{ url_for('admin.delete_links', link_id=link.id) }}" method="POST">
											<input class="btn btn-danger" type="submit" value="Delete">
										</form>
									</div>
								</div>
							</div>
						</div>
					{% endif %}
				{% endif %}
			{% endfor %}
			<br />
		{% endfor %}
		{% if current_user.is_authenticated and current_user.is_admin %}
			<hr />
			<a class="btn btn-lg btn-info" role="button" href="{{ url_for('admin.new_links') }}">Create Link</a>
		{% endif %}
	</div>
		
	
		
</div>
		
		<script>
			window.onload = function(){
				
				fetch('/links_group/').then(function(response){
					response.json().then(function(data){
						console.table(data);
					});
				});
			}

		</script>
		

{% endblock content %}

app/WebApp/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
	
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{{ url_for('static', filename='jquery/jquery-3.3.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='popper/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>

    {% if title %}
        <title>Web App - {{ title }}</title>
    {% else %}
        <title>Web App</title>
    {% endif %}
</head>
<body>
		{# get permissions into template #}
	{% set devops = namespace(rights=false) %}
	{% set production = namespace(rights=false) %}
	{% set procCtrl = namespace(rights=false) %}
	{% set maint = namespace(rights=false) %}
	{% set maintAdmin = namespace(rights=false) %}
	
	{% for right in current_user.rights %}
	
		{% if right.group == "DevOps"%}
			{% set devops.rights = true %}
		{% endif %}
		
		{% if right.group == "Production" %}
			{% set production.rights = true %}
		{% endif %}
		
		{% if right.group == "ProcessControl" %}
			{% set procCtrl.rights = true %}
		{% endif %}
		
		{% if right.group == "Maintenance" %}
			{% set maint.rights = true %}
		{% endif %}
		{% if right.group == "MaintAdmin" %}
			{% set maintAdmin.rights = true %}
		{% endif %}
		
	{% endfor %}
	
	
	
    <header class="site-header">
		<nav class="navbar navbar-expand-lg navbar-dark bg-steel fixed-top pre-scrollable">
				<!--Brand-->
			<a class="navbar-brand mr-4" href="#"><img alt="Brand" src="{{ url_for('static', filename='Resolute_Icon.jpg') }}" class="img-fluid" /></a>
			
				<!-- Toggler -->
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			
			<div class="collapse navbar-collapse my-nav" id="navbarToggle">
				<div class="container">
					<div class="navbar-nav mr-auto">
							<a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home | </a>
						<!-- ADMIN -->
					{% if current_user.is_authenticated %}
							{% if current_user.is_admin %}
								<div class="dropdown">
									<a class="nav-item nav-link" id="navbarDropdownAdmin" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin | </a>
									<div class="dropdown-menu" aria-labelledby="navbarDropdownAdmin">
									
											<a class="nav-item nav-link dropdown-toggle" id="navbarDropdownCM" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Credential Manager</a>
											<div class="dropdown-menu" aria-labelledby="navbarDropdownCM">
												<a class="nav-link" href="{{ url_for('admin.roles') }}">Roles</a>
												<a class="nav-link" href="{{ url_for('admin.register') }}">Register</a>
												<a class="nav-link" href="{{ url_for('admin.permissions') }}">Permissions</a>
											</div>
									</div>
								</div>
							{% endif %}
							
							<!-- DEV OPS -->
							{% if devops.rights or current_user.is_admin %}
								<div class="dropdown">
									<a class=" nav-item nav-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true" href="#"><span class="nav-label">Dev Ops | </span></a>
									<div class="dropdown-menu">
										<a class="nav-item nav-link" href="{{ url_for('dev_ops.api_new') }}">New API</a>
										<a class="nav-item nav-link" href="{{ url_for('dev_ops.api') }}">API</a>
									</div>
								</div>
							{% endif %}
							
							<!-- PRODUCTION -->
						{% endif %}
						
						{% if current_user.is_authenticated or current_user.is_admin %}
						<div class="dropdown">
							<a class=" nav-item nav-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true" href="#">Production | </a>
							<div class="dropdown-menu">
								{% if current_user.is_authenticated or current_user.is_admin %}
								<!--<a class="nav-item nav-link" href="{{ url_for('production.kpi') }}">KPI</a>
								<a class="nav-item nav-link" href="{{ url_for('production.kpi_new') }}">New KPI</a>-->
								<a class="nav-item nav-link" href="{{ url_for('production.mill_log') }}">Mill Log</a>
								<!--<a class="nav-item nav-link" href="{{ url_for('production.rcpe') }}">RCPE</a>
								<a class="nav-item nav-link" href="{{ url_for('production.rcpe_new') }}">New RCPE</a>
								<a class="nav-item nav-link" href="{{ url_for('production.action_items') }}">Action Items</a>-->
								{% endif %}
								<!--<a class="nav-item nav-link" href="{{ url_for('production.ae_comments') }}">AE Comments</a>-->
							</div>
						</div>
						{% endif %}
							
						{% if current_user.is_authenticated %}	
							<!-- INFORMATION TECHNOLOGY -->
							
							<!-- PROCESS CONTROL -->
							{% if procCtrl.rights or current_user.is_admin %}
								<div class="dropdown">
									<a class=" nav-item nav-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true" href="#"><span class="nav-label">Process Control | </span></a>
									<div class="dropdown-menu">
										<a class="nav-item nav-link" href="{{ url_for('process_control.inventory_pc') }}">PC Inventory</a>
									</div>
								</div>
							{% endif %}	
							
							<!-- MAINTENANCE -->
							{% if maint.rights or maintAdmin.rights or current_user.is_admin %}
								<div class="dropdown">
									<a class="nav-item nav-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true" href="#"><span class="nav-label">Maintenance | </span></a>
									<div class="dropdown-menu">
										<a class="nav-item nav-link" href="{{ url_for('maint.task_manage') }}">Task Manager</a>
									</div>
								</div>
							{% endif %}
							
						{% endif %}
					</div>
				</div>
			
				<!-- Navbar Right Side -->
				<div class="navbar-nav">
					<div class="navbar-nav mr-auto">
					
							<!-- USERS -->
						{% if current_user.is_authenticated %}
							<a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account | </a>
							<a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout </a>
						{% else %}
							<a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
						{% endif %}
					</div>
				</div>
			</div>
      </nav>
    </header>
    <main role="main">
      <div class="row">
        <div class="col-md-12 pt-2">
			{% with messages = get_flashed_messages(with_categories=true) %}
				{% if messages %}
					{% for category, message in messages %}
						<div class="alert alert-{{ category }}">
							{{ message }}
						</div>
					{% endfor %}
				{% endif %}
			{% endwith %}
		{% block content %}{% endblock %}
        </div>
        
      </div>
	  <!--
	  <div class="col-md-4 float-right">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
		  
        </div>-->
    </main>


    <!-- Optional JavaScript -->

</body>
</html>

app/WebApp/templates/register.html
{% extends "layout.html" %}
{% block content %}
	<h1>Register User</h1>
{% endblock content %}