app/WebApp/process_control/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import (StringField, IntegerField, SubmitField, SelectField, TextAreaField, DecimalField)
from wtforms.validators import DataRequired, Length, ValidationError
from WebApp.api.sqlite_tool import sqlite_api

db = "./app/WebApp/databases/inventory.db"

class InventoryQuestionareForm(FlaskForm):
    system = SelectField("What Best Describes Your Item?",
                         coerce=int,
                         validators=[DataRequired()])

    manufacturer = StringField("Manufacturer.",
                               validators=[DataRequired()])

    submit = SubmitField("Continue")

class InventoryUpdateForm(FlaskForm):
    item_name = StringField("Item Name",
                            validators=[DataRequired()])

    location_id = StringField("Locatino Id",
                              validators=[DataRequired()])

    quantity = IntegerField("Quantity",
                            validators=[DataRequired()])

    manufacturer = StringField("Manufacturer")

    model = StringField("Model")

    picture = FileField("Picture", validators=[FileAllowed(['jpg', 'png'])])

    part_number = StringField("Part Number")

    serial_number = StringField("Serial Number")

    details = TextAreaField("Details",
                            validators=[DataRequired()])

    category = StringField("Category",
                           validators=[DataRequired()])

    refItem = StringField("Reference Item",
                        validators=[DataRequired()])

    vendor = StringField("Vendor")

    sap_id = StringField(" SAP ID ")

    last_cost = DecimalField("Last Purchase Cost (dollar per unit)",
                             validators=[DataRequired()])

    submit = SubmitField(" Update Item ")

class InventoryForm(FlaskForm):
    item_name = StringField("Item Name",
                            validators=[DataRequired()])

    location_id = StringField("Locatino Id",
                              validators=[DataRequired()])

    quantity = IntegerField("Quantity",
                            validators=[DataRequired()])

    manufacturer = StringField("Manufacturer")

    model = StringField("Model")

    picture = FileField("Picture", validators=[FileAllowed(['jpg', 'png'])])

    part_number = StringField("Part Number")

    serial_number = StringField("Serial Number")

    details = TextAreaField("Details",
                            validators=[DataRequired()])

    category = StringField("Category",
                           validators=[DataRequired()])

    refItem = StringField("Reference Item",
                        validators=[DataRequired()])

    vendor = StringField("Vendor")

    sap_id = StringField(" SAP ID ")

    last_cost = DecimalField("Last Purchase Cost (dollar per unit)",
                             validators=[DataRequired()])

    submit = SubmitField(" Create Item ")

    def validate_location_id(self, location_id):
        sql = """ SELECT * FROM Inventory WHERE locationId = '{}' """.format(location_id.data)
        locationIds = sqlite_api(db, sql, "read")
        if locationIds:
            raise ValidationError("That Location is taken, Please contact administrator to fix this problem")

    def validate_part_number(self, part_number):
        sql = """ SELECT * FROM Inventory WHERE partNumber = '{}' """.format(part_number.data)
        partNumber = sqlite_api(db, sql, "read")
        if partNumber:
            raise ValidationError("An item with this part number already exists, please search inventory for this item.")

    def validate_serial_number(self, serial_number):
        sql = """ SELECT * FROM Inventory WHERE serialNumber = '{}' """.format(serial_number.data)
        serialNumber = sqlite_api(db, sql, "read")
        if serialNumber:
            raise ValidationError("An item with this serial number already exists, please search inventory for this item.")

    def validate_sap_id(self, sap_id):
        sql = """ SELECT * FROM Inventory WHERE SapId = '{}' """.format(sap_id.data)
        sapId = sqlite_api(db, sql, "read")
        if sapId:
            raise ValidationError("An item with this SAP Id already exists, please search inventory for this item.")

app/WebApp/process_control/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, jsonify
from flask_login import current_user, login_required
from WebApp.process_control.forms import (InventoryForm, InventoryUpdateForm, InventoryQuestionareForm)
from WebApp.api.sqlite_tool import sqlite_api
from WebApp.process_control.utils import (save_picture, delete_picture, send_log, filter_attributes, filter_objects)
import datetime
from datetime import timedelta, datetime
import json
import os

process_control = Blueprint('process_control', __name__)
db = "./app/WebApp/databases/inventory.db"

#IVENTORY#
@process_control.route('/pc/inventory')
@login_required
def inventory_pc():
    user_id = current_user.id
    
    inventory = []
    cart = []

    #get data from database#
    sql = """ SELECT * FROM Cart WHERE userId = {} """.format(user_id)
    cart = sqlite_api(db, sql, "read")
    
    sql = """ SELECT * FROM Inventory """
    inventory = sqlite_api(db, sql, "read")
    manufacturers = filter_attributes(inventory, "manufacturer")
    models = filter_attributes(inventory, "model")
    categories = filter_attributes(inventory, "category")
    ref_items = filter_attributes(inventory, "refItem")
    
    return render_template('process_control/inventory.html',
                           manufacturers = manufacturers,
                           models = models,
                           inventory = inventory,
                           ref_items = ref_items,
                           categories = categories,
                           cart = cart)

#CHECKOUT#
@process_control.route("/pc/inventory/cart/checkout")
@login_required
def inventory_cart_checkout():
    user_id = current_user.id
    sql = """ SELECT * FROM Cart WHERE userId = '{}' """.format(user_id)
    cart = sqlite_api(db, sql, 'read')
    item_ids = [item["inventoryId"] for item in cart]

    sql = """ SELECT * FROM Inventory WHERE""".format(user_id)
    for item in item_ids:
        if sql == """ SELECT * FROM Inventory WHERE""".format(user_id):
            sql = sql + " id = '{}'".format(item)
        else:
            sql = sql + " or id = '{}'".format(item)
    items = sqlite_api(db, sql, 'read')
    

    return render_template("process_control/checkout.html", cart=cart, items=items)

#COMPLETE CHECKOUT#
@process_control.route("/pc/inventory/cart/completeCheckout/<jsonObj>")
@login_required
def inventory_cart_completeCheckout(jsonObj):
    #GET DATA FROM DATABASE#
    sql = """ SELECT * FROM Inventory """
    
    objs = json.loads(jsonObj)
    for obj in objs:
        if sql == """ SELECT * FROM Inventory """:
            sql = sql + "WHERE id = '{}'".format(obj["itemId"])
        else:
            sql = sql + " or id = '{}'".format(obj["itemId"])

    items = sqlite_api(db, sql, 'read')

        #GET NEW QUANTITIES#
    data = []
    for obj in objs:
        for item in items:
            
            if int(obj["itemId"]) == item["id"]:
                
                #Compile data for retrieval#
                d = {
                    'itemName' : item['itemName'],
                    'rQuantity' : obj['quantity'],
                    'itemLocation' : item['locationId']
                    }
                data.append(d)
                
                #UPDATE DATABASE#
                new_quantity = item['quantity'] - int(obj["quantity"])
                sql = """ UPDATE Inventory SET quantity = '{}' WHERE id = '{}'""".format(new_quantity, item['id'])
                sqlite_api(db, sql, 'write')

                #REMOVE items from cart#
                sql = """ DELETE FROM cart WHERE userId = '{}' """.format(current_user.id)
                sqlite_api(db, sql, 'write')

    flash("Your items have been removed from inventory.","success")
    return render_template("process_control/inventory_retrieve_items.html", data = data)
    

#REMOVE ITEM FROM CART#
@process_control.route("/pc/inventory/cart/remove/<int:item_id>")
@login_required
def inventory_cart_remove(item_id):
    user_id = current_user.id
    sql = """ SELECT * FROM cart WHERE userId = '{}' """.format(user_id)
    user_cart = sqlite_api(db, sql, "read")
    item_ids = [item["inventoryId"] for item in user_cart]
    if item_id not in item_ids:
        flash("This item was not in your cart.","danger")
        return redirect(url_for("process_control.inventory_pc"))

    sql = """ DELETE FROM Cart WHERE userId = '{}' and inventoryId = '{}' """.format(user_id, item_id)
    sqlite_api(db, sql, 'write')

    flash("This item has been removed from your cart.", "success")
    return redirect(url_for('process_control.inventory_pc'))
    
        

#ADD ITEM TO CART#
@process_control.route("/pc/inventory/cart/<int:item_id>")
@login_required
def inventory_cart(item_id):
    user_id = current_user.id
    sql = """ SELECT * FROM cart WHERE userId = '{}' """.format(user_id)
    user_cart = sqlite_api(db, sql, "read")
    for item in user_cart:
        if item["inventoryId"] == item_id:
            flash("This item is already in your cart","danger")
            return redirect(url_for("process_control.inventory_pc"))
    
    sql = """ INSERT INTO cart (userId, InventoryId)
    VALUES ('{}', '{}'); """.format(user_id, item_id)
    sqlite_api(db, sql, "write")

    flash("Item has been added to cart.", "success")
    return redirect(url_for("process_control.inventory_pc"))

#VIEW ITEM IMAGE#
@process_control.route('/pc/inventory/displayImage/<int:item_id>')
@login_required
def inventory_display_image(item_id):

    sql = """ SELECT image, itemName FROM Inventory WHERE id = {} """.format(item_id)
    items = sqlite_api(db, sql, "read")
    item = items[0]

    return "<img src='{}' />".format(url_for('static', filename= 'InventoryPics/'+ item['image']))

#ITEM DETAILS#
@process_control.route('/pc/inventory/details/<int:item_id>')
@login_required
def inventory_details(item_id):
    user_id = current_user.id

    cart = []
    sql = """ SELECT * FROM Cart WHERE userId = {} """.format(user_id)
    cart = sqlite_api(db, sql, "read")

    sql = """ SELECT * FROM Inventory WHERE id = {} """.format(item_id)
    items = sqlite_api(db, sql, "read")
    item = items[0]

    return render_template("process_control/inventory_details.html", item = item, cart = cart)

#JSON RETURN#
@process_control.route('/pc/inventory/json/<string:value>')
def inventory_json(value):
    results = []

    #get data from database#
    sql = """ SELECT * FROM Inventory """
    results = sqlite_api(db, sql, "read")
    
    return jsonify(results)

#DELETE ITEM#
@process_control.route('/pc/inventory/delete/<int:item_id>', methods=["GET","POST"])
@login_required
def inventory_pc_delete(item_id):

    sql = """ DELETE FROM Inventory WHERE id = '{}' """.format(item_id)
    sqlite_api(db, sql, "write")

    # Send log #
    now_log = datetime.now()
    send_log(f'{current_user.username}, deleted item: {item_id} at {now_log}', 'InventoryActivity')
        
    flash("Item has been deleted", "success")
    return redirect (url_for("process_control.inventory_pc"))

#ANSWER QUESTIONARE FOR LOCATION ID#
@process_control.route('/pc/inventory/questionare', methods=["GET", "POST"])
@login_required
def inventory_pc_questionare():
    form = InventoryQuestionareForm()
    system_choices = [(0,""), (1,"Optical Drives"), (2, "Internal Computer Components"),
                      (3, "Computer Accessories"), (4, "Optical Data Storage"),
                      (5, "Hard Drives"), (6, "Computer Expansion Cards"), (7, "Computer Power Supplies"),
                       (8, "Network Devices"), (9, "ABB/Bailey"),
                       (10, "HTRC"), (11, "Mouse"), (12, "Keyboard"), (13, "Software")]
    form.system.choices = system_choices
    
    if form.validate_on_submit():
        system = form.system.data
        manufacturer = form.manufacturer.data
        selected = system_choices[system][0]

        switcher = {
                1: "PC1-1",
                2: "PC1-2",
                3: "PC1-3",
                4: "PC1-4",
                5: "PC1-5",
                6: "PC1-6",
                7: "PC1-7",
                8: "PC1-8",
                9: "ABB",
                10: "HTRC",
                11: "PC2-1",
                12: "PC2-2",
                13: "SFT1"
            }

        if selected == 13:
            location_id = switcher[selected] + "-" + manufacturer[0].upper()
        else:
            location_id = switcher[selected]

        sql = """ SELECT locationId FROM Inventory WHERE locationId LIKE "{}%" """.format(location_id)
        location_ids = []
        locations = sqlite_api(db, sql, "read")
        if locations:
            locations = [location["locationId"] for location in locations]
            
            location_numbers = []
            for location in locations:
                location_number = location.split('-')[-1]
                location_numbers.append(int(location_number))

            location_numbers.sort()

            for i in range(len(location_numbers) -1):
                first = location_numbers[i]
                second = location_numbers[i + 1]
                if (first + 1) == second:
                    pass
                else:
                    new_number = str(first + 1)
        else:
            new_number = "1"
        location_id = location_id + "-" + new_number

        return redirect(url_for("process_control.inventory_pc_new", location_id = location_id, manufacturer=manufacturer))
    return render_template("process_control/inventory_questionare.html", form=form)

#UPDATE ITEM#
@process_control.route('/pc/inventory/update/<int:item_id>', methods=["GET","POST"])
@login_required
def inventory_pc_update(item_id):

    sql = """ SELECT * FROM Inventory WHERE id = '{}' """.format(item_id)
    items = sqlite_api(db, sql, "read")
    item = items[0]
    if item['image']:
        picture_file = item['image']
        oldPic = item['image']
    
    form = InventoryUpdateForm()
    

app/WebApp/templates/process_control/checkout.html
{% extends "layout.html" %}
{% block content %}
	<h1>Process Control Inventory - Checkout</h1>
	
		<!--Items found-->
		<div class="container">
			<div class="main">
				
				<div class="row">
					<div class="col-md-4">
						<h3><strong>Item Name</strong></h3>
					</div>
					<div class="col-md-4">
						<h3><strong>Total In Stock</strong></h3>
					</div>
					<div class="col-md-4">
						<h3><strong>Quantity Selected</strong></h3>
					</div>
				</div>
				{% for item in items %}
				<div class="row">
					<div class="col-md-4">
						<h3>{{item.itemName}}</h3>
					</div>
					<div class="col-md-4 stockQuantity">
						<h3>{{item.quantity}}</h3>
					</div>
					<div class="col-md-4 itemQuantity">
						<span><a href="#" class="btn btn-info btn-sm quantitySub">-</a></span>
						<span id="quantity{{item.id}}" class="quantity">0</span>
						<span><a href="#" class="btn btn-info btn-sm quantityAdd">+</a></span>
					</div>
				</div>
				
				<br />
				{% endfor %}
			</div>
			<!--Complete Checkout-->
			<hr />
			<a class="btn btn-primary float-right" id="btnCompleteCheckout" href="#">Checkout</a>
		</div>
		
		<script src="{{ url_for('static', filename='inventoryCheckout.js') }}"></script>


{% endblock content %}

app/WebApp/templates/process_control/inventory.html
{% extends "layout.html" %}
{% block content %}
	<h1>Process Control Inventory</h1>
	<a class="btn btn-outline-primary btn-sm" href="{{url_for('process_control.inventory_pc_questionare')}}">New Item</a>
	<hr />
	
	<!--Search-->
	<input type="text" id="txtId" placeholder="Search..." />
	<button class="btn btn-outline-info btn-md btnSearch">search</button>
	
	

		<!--Side bar-->
		<div class="sidenav">
			<h3>Filter</h3>
			<br />
			<div class="sidenav-content">
				<h5><strong>Manufacturer</strong></h5>
				<hr />
				
				<ul id="manList" class="form-check">
					{% for man in manufacturers %}
					<li><input type="checkbox" class="form-check-input" id="Man{{loop.index}}" value="" checked />{{man}}</li>
					{% endfor %}
				</ul>
				<br />
				
				<h5><strong>Model</strong></h5>
				<hr />
				<ul id="modList" class="form-check">
					{% for mod in models %}
					<li><input type="checkbox" class="form-check-input" id="Mod{{loop.index}}" checked />{{ mod }}</li>
					{% endfor %}
				</ul>
				<br />
				
				<h5><strong>Category</strong></h5>
				<hr />
				<ul id="catList" class="form-check">
					{% for cat in categories %}
					<li><input type="checkbox" class="form-check-input" id="Cat{{loop.index}}" checked />{{ cat }}</li>
					{% endfor %}
				</ul>
				<br />
				
				<h5><strong>Reference Item</strong></h5>
				<hr />
				<ul id="refList" class="form-check">
					{% for ref in ref_items %}
					<li><input type="checkbox" class="form-check-input" id="Ref{{loop.index}}" checked />{{ref}}</li>
					{% endfor %}
				</ul>
			</div>
			<button id="btnFilter" class="btn btn-info btn-sm m-3">Apply Filter</button>
		</div>
		
	
		<!--Items found-->
		<div class="container">
			<div class="main item-section">
				{% for item in inventory %}
				<div class="divItems">
					<div class="row">
						<div class="col-md-2">
							<a href="{{url_for('process_control.inventory_display_image', item_id = item.id)}}"><img class="itemImage" src="{{ url_for('static', filename='InventoryPics/' + item.image) }}" /></a>
						</div>
						<div class="col-md-6">
							<div class="row">
								<div class="col-sm-12">
									<h3 class="itemName"><a class="float-center" href="{{url_for('process_control.inventory_details', item_id = item.id)}}">{{ item.itemName }}</a></h3>
								</div>
							</div>
							<div class="row">
								<div class="col-sm-4">
									<h5 class="itemManufacturer">{{item.manufacturer}}</h5>
								</div>
								<div class="col-sm-4">
									<h5 class="itemModel">{{item.model}}</h5>
								</div>
								<div class="col-sm-4">
									<h5><strong>{{item.quantity}} in stock</strong></h5>
								</div>
							</div>
							<div class="row">
								<div class="col-md-4">
									<h5 class="itemCategory">{{item.category}}</h5>
								</div>
								<div class="col-md-4">
									<h5 class="itemRef">{{item.refItem}}</h5>
								</div>
								<div class="col-md-4">
									<h5 class="itemLastCost">${{ item.LastCost }} per unit</h5>
								</div>
							</div>
							<div class="row">
								<!--Serial Number, Details Part Number, Location Id, SAP Id, lastCost, vendor-->
								<div class="col-md-2">
									<h5 class="itemSN">{{item.serialNumber}}</h5>
								</div>
								<div class="col-md-2">
									<h5 class="itemPN">{{item.partNumber}}</h5>
								</div>
								<div class="col-md-2">
									<h5 class="itemLocationId">{{item.locationId}}</h5>
								</div>
								<div class="col-md-2">
									<h5 class="itemSapId">{{item.SapId}}</h5>
								</div>
								<div class="col-md-2">
									<h5 class="itemDetails">{{item.details}}</h5>
								</div>
								<div class="col-md-2">
									<h5 class="itemVendor">{{item.vendor}}</h5>
								</div>
							</div>
						</div>
						<div class="col-md-2">
							{% if item.id in cart | map(attribute='inventoryId')%}
							<a href="{{url_for('process_control.inventory_cart_remove', item_id = item.id)}}" class="btn btn-danger btn-md cartlink">Remove From Cart</a>
							{% else %}
							<a href="{{url_for('process_control.inventory_cart', item_id = item.id)}}" class="btn btn-info btn-md cartlink">Add To Cart</a>
							{% endif %}
						</div>
						
					</div>
					<br />
					<br />
				</div>
				
				{% endfor %}
			</div>
			
			<hr />
			<!-- Pagination -->
			<div><ul class="pagination"></ul></div>
			
			<!--Go To Checkout-->
			<a class="btn btn-primary float-right" href="{{url_for('process_control.inventory_cart_checkout')}}">Go To Checkout</a>
		</div>

	
	<script src="{{ url_for('static', filename='inventory.js') }}"></script>
	

{% endblock content %}

app/WebApp/templates/process_control/inventory_details.html
{% extends "layout.html" %}
{% block content %}
	<h1>Process Control Inventory - Details - {{ item.itemName }}</h1>
	
	<br />
	<a href="{{url_for('process_control.inventory_display_image', item_id = item.id)}}"><img src="{{url_for('static', filename='InventoryPics/'+ item.image)}}"></a>
	
	<hr />
		<div class="container">
			<div class="row">
				<div class="col-md-6 ">
					<h4><strong>Manufacturer:</strong> {{item.manufacturer}}</h4>
					<h4><strong>Model:</strong> {{item.model}}</h4>
					<h4><strong>Part Number:</strong> {{ item.partNumber }}</h4>
					<h4><strong>Serial Number:</strong> {{ item.serialNumber }}</h4>
					<h4><strong>Category:</strong> {{ item.category }}</h4>
				</div>
				<div class="col-md-6 ">
					<h4><strong>In Stock:</strong> {{ item.quantity }}</h4>
					<h4><strong>Reference Item:</strong> {{ item.refItem }}</h4>
					<h4><strong>Vendor:</strong> {{ item.vendor }}</h4>
					<h4><strong>SAP ID:</strong> {{ item.SapId }}</h4>
					<h4><strong>Last Purchase Cost:</strong> ${{ item.LastCost }} per unit</h4>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-12">
					<h4><strong>Details:</strong></h4>
					<h4>{{item.details}}</h4>
				</div>
			</div>
		</div>
		<hr />
		{% if item.id in cart | map(attribute= 'inventoryId') %}
		<a href="{{url_for('process_control.inventory_cart_remove', item_id = item.id)}}" class="btn btn-danger btn-md ">Remove From Cart</a><br /><br />
		{%else%}
		<a href="{{url_for('process_control.inventory_cart', item_id = item.id)}}" class="btn btn-info btn-md ">Add To Cart</a><br /><br />
		{% endif %}
		<a href="{{url_for('process_control.inventory_pc_update', item_id = item.id)}}" class="btn btn-secondary btn-md ">Update</a><br /><br />
		<!--<a href="#" class="btn btn-danger btn-md ">Delete</a><br /><br />-->
		<button type="button" class="btn btn-danger btn-md m-1" data-toggle="modal" data-target="#deleteModal{{item.id}}">Delete</button>
		
			<!--Delete Item Modal-->
		<div class="modal fade" id="deleteModal{{item.id}}" tabindex="-1" role="dialog" aria-labelledby="deleteModallabel" aria-hidden="true">
				<div class="modal-dialog" role="document">
					<div class="modal-content">
						<div class="header">
							<h5 class="modal-title" id="deleteModallabel{{item.id}}">Delete Link</h5>
							<button type="button" class="close" data-dismiss="modal" aria-label="Close">
								<span aria-hidden="true">&times;</span>
							</button>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
							<form action="{{ url_for('process_control.inventory_pc_delete', item_id=item.id) }}" method="POST">
								<input class="btn btn-danger" type="submit" value="Delete">
							</form>
						</div>
					</div>
				</div>
			</div>

{% endblock content %}

app/WebApp/templates/process_control/inventory_questionare.html
{% extends "layout.html" %}
{% block content %}
	<h1>Process Control Inventory - Questionare</h1>
	
	<div class="container">
		<form method="POST" action="", enctype="multipart/form-data">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottm mb-4"> {{ legend }} </legend>

					<!-- system -->
				<div class="form-group">
					{{ form.system.label(class="form-control-label") }}
					{% if form.system.errors %}
						{{ form.system(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.system.errors %}
								<span> {{ error }} </span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.system(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				
					<!--manufacturer-->
				<div class="form-group">
					{{ form.manufacturer.label(class="form-control-label") }}
					{% if form.manufacturer.errors %}
						{{ form.manufacturer(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.manufacturer.errors %}
								<span> {{ error }} </span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.manufacturer(class="form-control form-control-lg") }}
					{% endif %}
				</div>

			</fieldset>
				<!-- submit -->
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
{% endblock content %}

app/WebApp/templates/process_control/inventory_retrieve_items.html
{% extends "layout.html" %}
{% block content %}
	<h1>Process Control Inventory - Retrieve Items</h1>
	
	<div class="container">
		<div class="row">
			<div class="col-md-4">
				<h3><strong>Item Name</strong></h3>
			</div>
			<div class="col-md-4">
				<h3><strong>Retrieve Quantity</strong></h3>
			</div>
			<div class="col-md-4">
				<h3><strong>Item Location</strong></h3>
			</div>
		</div>
		
		<div class="row">
			{% for d in data%}
			<div class="col-md-4">
				<h3>{{d.itemName}}</h3>
			</div>
			<div class="col-md-4">
				<h3>{{d.rQuantity}}</h3>
			</div>
			<div class="col-md-4">
				<h3>{{d.itemLocation}}</h3>
			</div>
			{% endfor %}
		</div>
	</div>
	
{% endblock content %}