app/WebApp/maint/forms.py
from flask_wtf import FlaskForm
from wtforms import (StringField, SubmitField, SelectField,
                    IntegerField)
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired, Length, ValidationError

class ItemForm(FlaskForm):
    name = StringField('Name',
                       validators =[DataRequired()])

    lubricant = StringField('Lubricant',
                            validators=[DataRequired()])

    points = StringField('Points',
                         validators=[DataRequired()])

    equipment = SelectField(u'Equipment',
                            coerce=int,
                            validators=[DataRequired()])

    submit = SubmitField('Submit')


class AreaForm(FlaskForm):
    name = StringField('Name',
                       validators= [DataRequired()])

    submit = SubmitField('Submit')

class EquipmentForm(FlaskForm):
    title = StringField('Title',
                        validators=[DataRequired()])

    area = SelectField('Area',
                       coerce=int,
                       validators=[DataRequired()])

    submit = SubmitField('Submit')

class TaskForm(FlaskForm):
    name = StringField('Name',
                       validators=[DataRequired()])

    item = SelectField('Item',
                       coerce=int,
                       validators=[DataRequired()])

    DateDue = DateField('Date Due',
                        format='%Y-%m-%d',
                        validators=[DataRequired()])

    frequencyNumber = IntegerField('Frequency Number',
                                   validators=[DataRequired()])

    frequencyFormat = SelectField('Frequency Format',
                                  coerce=int,
                                  validators=[DataRequired()])

    submit = SubmitField('Submit')

app/WebApp/maint/routes.py
from flask import (render_template, url_for, flash, redirect,
                   request, Blueprint, jsonify, abort, request)
from operator import itemgetter
import datetime
from datetime import timedelta, datetime
from WebApp.maint.utils import (filter_tasks,
                                filter_objects,
                                combine_objects,
                                get_new_due_date)
from WebApp.maint.forms import (ItemForm, AreaForm, EquipmentForm, TaskForm)
from WebApp.maint.sqlite_tool import sqlite_api
from flask_login import current_user, login_required
from WebApp.models import User, Role
from WebApp import db


maint = Blueprint('maint', __name__)
task_db = "./app/WebApp/databases/equipment.db"


@maint.route('/maint/tasks', methods=('GET', 'POST'))
@login_required
def task_manage():
    if not current_user.is_admin:
        user = User.query.filter_by(id=current_user.id).first()
        rights = [right.group for right in user.rights]
        if not 'MaintAdmin' in rights:
            if not 'Maintenance' in rights:
                abort(403)
    return render_template('maint/tasks.html', title='Task Manage')

@maint.route('/tasks/complete/<int:task_id>')
@login_required
def complete_tasks(task_id):
    if not current_user.is_admin:
        user = User.query.filter_by(id=current_user.id).first()
        rights = [right.group for right in user.rights]
        if not 'MaintAdmin' in rights:
            if not 'Maintenance' in rights:
                abort(403)
            
    today = datetime.today().strftime('%Y-%m-%d')
    sql = """ SELECT frequency_number, frequency_format from tasks WHERE id='{}' """.format(task_id)
    adjust_date = sqlite_api(task_db, sql, 'read')
    fn = adjust_date[0]['frequency_number']
    ff = adjust_date[0]['frequency_format']
    due_date = get_new_due_date(ff,fn)
    print(ff)
    if due_date == None:
        abort(403)

    sql = """ UPDATE tasks SET date_completed = '{}', date_due = '{}' WHERE id='{}' """.format(today, due_date, task_id)
    sqlite_api(task_db, sql, 'write')
    
    flash('Task Completed','success')
    return redirect(url_for('maint.task_manage'))


    #ITEMS SECTION#
@maint.route('/tasks/new/item', methods=('GET','POST'))
@login_required
def new_item():
    if not current_user.is_admin:
        user = User.query.filter_by(id=current_user.id).first()
        rights = [right.group for right in user.rights]
        if not 'MaintAdmin' in rights:
            if not 'Maintenance' in rights:
                abort(403)
                
    form = ItemForm()
    
    sql = """ SELECT * FROM equipment """
    equipment = sqlite_api(task_db, sql, 'read')
    equipment = sorted(equipment, key=itemgetter('title'))
    if request.method == "GET":
        form.equipment.choices = [(int(equip['id']), equip['title']) for equip in equipment]
    elif request.method == "POST":
        name = form.name.data
        lubricant = form.lubricant.data
        points = int(form.points.data)
        equipment = form.equipment.data

        sql = """ INSERT INTO items(name, lubricant, points, equip_id)VALUES('{}','{}',{},{}) """.format(name,lubricant,points,equipment)
        sqlite_api(task_db, sql, 'write')

        flash('Your Item has been created','success')
        return redirect(url_for('maint.task_manage'))
    return render_template('maint/new_item.html', form=form, legend="Create Item", title="Create Item")

@maint.route('/tasks/update/item/<int:item_id>', methods=('GET','POST'))
@login_required
def update_item(item_id):
    if not current_user.is_admin:
        user = User.query.filter_by(id=current_user.id).first()
        rights = [right.group for right in user.rights]
        if not 'MaintAdmin' in rights:
            if not 'Maintenance' in rights:
                abort(403)

    form = ItemForm()
    sql = """ SELECT * FROM items WHERE id = {} """.format(item_id)
    item = sqlite_api(task_db, sql, 'read')
    item = item[0]

    sql = """ SELECT * FROM equipment """
    equipment = sqlite_api(task_db, sql, 'read')
    equipment = sorted(equipment, key=itemgetter('title'))
                
    if request.method == "GET":
        form.name.data = item['name']
        form.lubricant.data = item['lubricant']
        form.points.data = item['points']
        form.equipment.choices = [(int(equip['id']), equip['title']) for equip in equipment]
    elif request.method == "POST":
        name = form.name.data
        lubricant = form.lubricant.data
        points = int(form.points.data)
        equipment = form.equipment.data

        sql = """ UPDATE items SET name='{}', lubricant='{}', points={}, equipment='{}' WHERE id={}""".format(name, lubricant, points, equipment, item_id)
        sqlite_api(task_db, sql, 'read')

        flash('Your Item has been updated.','success')
        return redirect(url_for('maint.task_manage'))
    return render_template('/maint/new_item.html', legend='Update Item', title= "Update Item", form=form)

@maint.route('/tasks/delete/item/<int:item_id>')
def delete_item(item_id):
    if not current_user.is_admin:
        user = User.query.filter_by(id=current_user.id).first()
        rights = [right.group for right in user.rights]
        if not 'MaintAdmin' in rights:
            if not 'Maintenance' in rights:
                abort(403)
                
    sql = """ DELETE FROM items WHERE id={} """.format(item_id)
    sqlite_api(task_db, sql, 'write')
    
    flash('You item has been removed.','success')
    return redirect(url_for('maint.task_manage'))


    #AREA SECTION#
@maint.route('/tasks/new/area', methods=('GET','POST'))
def new_area():
    if not current_user.is_admin:
        user = User.query.filter_by(id=current_user.id).first()
        rights = [right.group for right in user.rights]
        if not 'MaintAdmin' in rights:
            if not 'Maintenance' in rights:
                abort(403)

    form = AreaForm()

    if request.method == "POST":
        name = form.name.data

        sql= """ INSERT INTO area(name) VALUES('{}') """.format(name)
        sqlite_api(task_db, sql, 'write')

        flash("Your Area has been created", 'success')
        return redirect(url_for('maint.task_manager'))
    return render_template('maint/new_area.html', form=form, legend="Create Area", title= "Create Area")

@maint.route('/tasks/update/area/<int:area_id>', methods=('GET','POST'))
@login_required
def update_area(area_id):
    if not current_user.is_admin:
        user = User.query.filter_by(id=current_user.id).first()
        rights = [right.group for right in user.rights]
        if not 'MaintAdmin' in rights:
            if not 'Maintenance' in rights:
                abort(403)

    form = AreaForm()
    sql = """ SELECT * FROM areas WHERE id = {} """.format(area_id)
    area = sqlite_api(task_db, sql, 'read')
    area = area[0]
                
    if request.method == "GET":
        form.name.data = area['name']
    elif request.method == "POST":
        name = form.name.data

        sql = """ UPDATE areas SET name='{}'WHERE id={}""".format(name, area_id)
        sqlite_api(task_db, sql, 'read')

        flash('Your Area has been updated.','success')
        return redirect(url_for('maint.task_manage'))
    return render_template('/maint/new_area.html', legend='Update Area', title= "Update Area", form=form)


@maint.route('/tasks/delete/area/<int:area_id>')
def delete_area(area_id):
    if not current_user.is_admin:
        user = User.query.filter_by(id=current_user.id).first()
        rights = [right.group for right in user.rights]
        if not 'MaintAdmin' in rights:
            if not 'Maintenance' in rights:
                abort(403)
                
    sql = """ DELETE FROM areas WHERE id={} """.format(area_id)
    sqlite_api(task_db, sql, 'write')
    
    flash('You area has been removed.','success')
    return redirect(url_for('maint.task_manage'))


    # EQUIPMENT SECTION #
@maint.route('/tasks/new/equipment', methods=('GET','POST'))
def new_equipment():
    if not current_user.is_admin:
        user = User.query.filter_by(id=current_user.id).first()
        rights = [right.group for right in user.rights]
        if not 'MaintAdmin' in rights:
            if not 'Maintenance' in rights:
                abort(403)
                
    form = EquipmentForm()

    sql = """ SELECT * FROM areas """
    areas = sqlite_api(task_db, sql, 'read')
    areas = sorted(areas, key=itemgetter('name'))
    
    if request.method == "GET":
        form.area.choices = [(int(area['id']), area['name']) for area in areas]
    elif request.method == "POST":
        title = form.title.data
        area = form.area.data

        sql = """ INSERT INTO equipment(title, area_id)VALUES('{}',{}) """.format(title, area)
        sqlite_api(task_db, sql, 'write')

        flash('Your Equipment has been created','success')
        return redirect(url_for('maint.task_manage'))
    return render_template('maint/new_equipment.html', form=form, legend="Create Equipment", title="Create Equipment")

@maint.route('/tasks/update/equipment/<int:equip_id>', methods=('GET','POST'))
@login_required
def update_equipment(equip_id):
    if not current_user.is_admin:
        user = User.query.filter_by(id=current_user.id).first()
        rights = [right.group for right in user.rights]
        if not 'MaintAdmin' in rights:
            if not 'Maintenance' in rights:
                abort(403)

    form = EquipmentForm()
    sql = """ SELECT * FROM equipment WHERE id = {} """.format(equip_id)
    equipment = sqlite_api(task_db, sql, 'read')
    equipment = equipment[0]

    sql = """ SELECT * FROM areas """
    areas = sqlite_api(task_db, sql, 'read')
    areas = sorted(areas, key=itemgetter('name'))
                
    if request.method == "GET":
        form.title.data = equipment['title']
        form.area.choices = [(int(area['id']), area['name'])for area in areas]
    elif request.method == "POST":
        title = form.title.data

app/WebApp/templates/maint/action_items.html
{% extends "layout.html" %}
{% block content %}
	<h1>Action Items PAGE</h1>
{% endblock content %}

app/WebApp/templates/maint/new_area.html
{% extends 'layout.html' %}
{% block content %}
	<div class="container">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottm mb-4"> {{ legend }} </legend>

					<!-- name -->
				<div class="form-group">
					{{ form.name.label(class="form-control-label") }}
					{% if form.name.errors %}
						{{ form.name(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.name.errors %}
								<span> {{ error }} </span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.name(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>

			
		</form>
	</div>
{% endblock content %}

app/WebApp/templates/maint/new_equipment.html
{% extends 'layout.html' %}
{% block content %}
	<div class="container">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottm mb-4"> {{ legend }} </legend>

					<!-- title -->
				<div class="form-group">
					{{ form.title.label(class="form-control-label") }}
					{% if form.title.errors %}
						{{ form.title(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.title.errors %}
								<span> {{ error }} </span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.title(class="form-control form-control-lg") }}
					{% endif %}
				</div>

					<!-- area -->
				<div class="form-group">
					{{ form.area.label(class="form-control-label") }}
					{% if form.area.errors %}
						{{ form.area(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.area.errors %}
								<span> {{ error }} </span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.area(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				
				
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>

			
		</form>
	</div>
{% endblock content %}

app/WebApp/templates/maint/new_item.html
{% extends 'layout.html' %}
{% block content %}
	<div class="container">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottm mb-4"> {{ legend }} </legend>

					<!-- name -->
				<div class="form-group">
					{{ form.name.label(class="form-control-label") }}
					{% if form.name.errors %}
						{{ form.name(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.name.errors %}
								<span> {{ error }} </span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.name(class="form-control form-control-lg") }}
					{% endif %}
				</div>

					<!-- lubricant -->
				<div class="form-group">
					{{ form.lubricant.label(class="form-control-label") }}
					{% if form.lubricant.errors %}
						{{ form.lubricant(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.lubricant.errors %}
								<span> {{ error }} </span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.lubricant(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				
				<!-- points -->
				<div class="form-group">
					{{ form.points.label(class="form-control-label") }}
					{% if form.points.errors %}
						{{ form.points(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.points.errors %}
								<span> {{ error }} </span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.points(class="form-control form-control-lg") }}
					{% endif %}
				</div>

				<!-- equipment -->
				<div class="form-group">
					{{ form.equipment.label(class="form-control-label") }}
					{% if form.equipment.errors %}
						{{ form.equipment(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.equipment.errors %}
								<span> {{ error }} </span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.equipment(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>

			
		</form>
	</div>
{% endblock content %}

app/WebApp/templates/maint/new_task.html
{% extends 'layout.html' %}
{% block content %}
	<div class="container">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottm mb-4"> {{ legend }} </legend>

					<!-- name -->
				<div class="form-group">
					{{ form.name.label(class="form-control-label") }}
					{% if form.name.errors %}
						{{ form.name(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.name.errors %}
								<span> {{ error }} </span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.name(class="form-control form-control-lg") }}
					{% endif %}
				</div>

					<!-- item -->
				<div class="form-group">
					{{ form.item.label(class="form-control-label") }}
					{% if form.item.errors %}
						{{ form.item(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.item.errors %}
								<span> {{ error }} </span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.item(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				
				<!-- DateDue -->
				<div class="form-group">
					{{ form.DateDue.label(class="form-control-label") }}
					{% if form.DateDue.errors %}
						{{ form.DateDue(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.DateDue.errors %}
								<span> {{ error }} </span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.DateDue(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				
				<!-- frequencyNumber -->
				<div class="form-group">
					{{ form.frequencyNumber.label(class="form-control-label") }}
					{% if form.frequencyNumber.errors %}
						{{ form.frequencyNumber(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.frequencyNumber.errors %}
								<span> {{ error }} </span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.frequencyNumber(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				
				<!-- frequencyFormat -->
				<div class="form-group">
					{{ form.frequencyFormat.label(class="form-control-label") }}
					{% if form.frequencyFormat.errors %}
						{{ form.frequencyFormat(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.frequencyFormat.errors %}
								<span> {{ error }} </span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.frequencyFormat(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				
				
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>

			
		</form>
	</div>
{% endblock content %}

app/WebApp/templates/maint/tasks.html
{% extends 'layout.html' %}
{% block content %}
	{% set maintAdmin = namespace(rights=false) %}
	{% for right in current_user.rights %}
		{% if right.group == "MaintAdmin" %}
			{% set maintAdmin.rights = true %}
		{% endif %}
	{% endfor %}
	<div class="container">
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark pre-scrollable">
	
		<h3 href="#" class="navbar-brand mr-4">At A Glance</h3>
			
			<!-- Toggler -->
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar2Toggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		
			
		<div class="collapse navbar-collapse" id="navbar2Toggle">
			<div class="container">
				<div class="navbar-nav mr-auto" id="nav2">
					<a class="nav-item nav-link" href="#">Past Due</a>
					<a class="nav-item nav-link" href="#">Today</a>
					<a class="nav-item nav-link" href="#">Tomorrow</a>
					<a class="nav-item nav-link" href="#">This Week</a>
					<a class="nav-item nav-link" href="#">Next Week</a>
					<a class="nav-item nav-link" href="#">Next Outage</a>
					<a class="nav-item nav-link" href="#">Annual</a>
					<a class="nav-item nav-link" href="#">All</a>
					
				</div>	
			</div>
			{% if current_user.is_admin or maintAdmin.rights %}
				<!-- Navbar Right Side -->
				<div class="navbar-nav">
					<div class="navbar-nav mr-auto">
						<a class="nav-item nav-link" href="#">Schedule</a>
					</div>
				</div>
			{% endif %}
		</div>
	</nav>

		<div class="container">
			<h2 class="text-center" id="contentHeader"></h2>
			
				<!-- AREA tabs -->
			<ul id="nav" class="nav nav-tabs" role="tablist"></ul>
			
			<div class="tab-content clearfix">
					<div id="modArea"></div>
					<div class="col-md-6 float-left" id="divEquip">
						<h1>Equipment</h1>
						<table class="table table-hover table-striped table-responsive-lg scroll-y">
						<thead class="thead-dark">
							<tr>
								<th>Title</th>
								{% if current_user.is_admin or maintAdmin.rights %}
									<th>Update</th>
									<th>Delete</th>
								{% endif %}
							</tr>
						</thead>
						<tbody id="tblEquip"></tbody>
						</table>
						{% if current_user.is_admin or maintAdmin.rights %}
							<a class="btn btn-md btn-info" role="button" href="{{url_for('maint.new_equipment')}}">Create Equipment</a>
						{% endif %}
					</div>
					
					<div class="col-md-6 float-right" id="divItem">
						<h1>Items</h1>
						<table class="table table-hover table-striped table-responsive-lg scroll-y">
						<thead class="thead-dark">
							<tr>
								<th>Name</th>
								{% if current_user.is_admin or maintAdmin.rights %}
									<th>Update</th>
									<th>Delete</th>
								{% endif %}
							</tr>
						</thead>
						<tbody id="tblItem"></tbody>
						</table>
						{% if current_user.is_admin or maintAdmin.rights %}
							<a class="btn btn-md btn-info" role="button" href="{{url_for('maint.new_item')}}">Create Item</a>
						{% endif %}
					</div>
					
			</div>
		</div>
		<hr />
		
		<div class="container text-center" id="divTask">
			<h1 class="text-center">Tasks</h1>
			<table class="table table-striped table-hover table-responsive-lg" >
				<thead class="thead-dark">
					<tr>
						<th>Name</th>
						<th>Date Due</th>
						<th>Complete</th>
						{% if current_user.is_admin or maintAdmin.rights %}
							<th id="maintAdmin">Update</th>
							<th>Delete</th>
						{% endif %}
					</tr>
				</thead>
				<tbody id="tblTask"></tbody>
			</table>
			{% if current_user.is_admin or maintAdmin.rights %}
				<a class="btn btn-md btn-info" role="button" href="{{url_for('maint.new_task')}}">Create Task</a>
			{% endif %}
		</div>

	</div>

	
	<!-- Modal -->
	<div class="divModal"></div>

	
	 <script src="{{ url_for('static', filename='maint_taskManager.js') }}"></script>
{% endblock content %}